export class FileType {

  static defaultFileType: FileType = new FileType("other");

  static supportedFileTypes: FileType[] = [
    new FileType("pp"),
    new FileType("css"),
    new FileType("csv"),
    new FileType("py"),
    new FileType("wsf"),
    new FileType("hs"),
    new FileType("ost"),
    new FileType("midi"),
    new FileType("exe"),
    new FileType("java"),
    new FileType("nim"),
    new FileType("bat"),
    new FileType("mov"),
    new FileType("xml"),
    new FileType("jar"),
    new FileType("adoc"),
    new FileType("scm"),
    new FileType("zip"),
    new FileType("otf"),
    new FileType("clj"),
    new FileType("exs"),
    new FileType("rar"),
    new FileType("7z"),
    new FileType("mpg"),
    new FileType("tex"),
    new FileType("png"),
    new FileType("ai"),
    new FileType("torrent"),
    new FileType("eps"),
    new FileType("ra"),
    new FileType("cdr"),
    new FileType("rb"),
    new FileType("dwf"),
    new FileType("groovy"),
    new FileType("sln"),
    new FileType("dwg"),
    new FileType("doc"),
    new FileType("accdb"),
    new FileType("odp"),
    new FileType("rm"),
    new FileType("odt"),
    new FileType("aif"),
    new FileType("ods"),
    new FileType("rs"),
    new FileType("jl"),
    new FileType("other"),
    new FileType("log"),
    new FileType("vbs"),
    new FileType("jsp"),
    new FileType("flac"),
    new FileType("js"),
    new FileType("mid"),
    new FileType("vmdk"),
    new FileType("wma"),
    new FileType("kml"),
    new FileType("dart"),
    new FileType("fcp"),
    new FileType("sh"),
    new FileType("pgn"),
    new FileType("epub"),
    new FileType("jpeg"),
    new FileType("mobi"),
    new FileType("rkt"),
    new FileType("key"),
    new FileType("erl"),
    new FileType("xlsx"),
    new FileType("wmv"),
    new FileType("mat"),
    new FileType("c"),
    new FileType("rtf"),
    new FileType("svg"),
    new FileType("cfg"),
    new FileType("max"),
    new FileType("tgz"),
    new FileType("f"),
    new FileType("h"),
    new FileType("hpp"),
    new FileType("kt"),
    new FileType("cfm"),
    new FileType("m"),
    new FileType("docx"),
    new FileType("tc"),
    new FileType("cs"),
    new FileType("txt"),
    new FileType("flv"),
    new FileType("r"),
    new FileType("dproj"),
    new FileType("ppt"),
    new FileType("v"),
    new FileType("php"),
    new FileType("vdi"),
    new FileType("asm"),
    new FileType("pyc"),
    new FileType("db"),
    new FileType("asp"),
    new FileType("ts"),
    new FileType("msg"),
    new FileType("swf"),
    new FileType("bmp"),
    new FileType("iso"),
    new FileType("scss"),
    new FileType("numbers"),
    new FileType("project"),
    new FileType("vhdl"),
    new FileType("ogg"),
    new FileType("tif"),
    new FileType("dv"),
    new FileType("pages"),
    new FileType("ma"),
    new FileType("mb"),
    new FileType("vcxproj"),
    new FileType("md"),
    new FileType("aspx"),
    new FileType("veg"),
    new FileType("mkv"),
    new FileType("html"),
    new FileType("ogv"),
    new FileType("swift"),
    new FileType("ml"),
    new FileType("yaml"),
    new FileType("cpp"),
    new FileType("pas"),
    new FileType("tar"),
    new FileType("sqlite"),
    new FileType("lisp"),
    new FileType("mdb"),
    new FileType("fcpx"),
    new FileType("less"),
    new FileType("mli"),
    new FileType("vb"),
    new FileType("pptx"),
    new FileType("ex"),
    new FileType("mpeg"),
    new FileType("psd"),
    new FileType("tiff"),
    new FileType("gif"),
    new FileType("aiff"),
    new FileType("scala"),
    new FileType("blend"),
    new FileType("prproj"),
    new FileType("for"),
    new FileType("aep"),
    new FileType("fs"),
    new FileType("sql"),
    new FileType("xsl"),
    new FileType("pst"),
    new FileType("avi"),
    new FileType("yml"),
    new FileType("bz2"),
    new FileType("m4a"),
    new FileType("tcl"),
    new FileType("htm"),
    new FileType("jpg"),
    new FileType("ttf"),
    new FileType("go"),
    new FileType("wav"),
    new FileType("mp4"),
    new FileType("cbp"),
    new FileType("mp3"),
    new FileType("pdf"),
    new FileType("vhd"),
    new FileType("gz"),
    new FileType("coffee"),
    new FileType("lua"),
    new FileType("pub"),
    new FileType("pl"),
    new FileType("f90"),
    new FileType("xls"),
    new FileType("dmg")];

  static fromFileEnding(fileEnding: string) {
    for (const supportedFileType of this.supportedFileTypes) {
      if(supportedFileType.fileEnding === fileEnding){
        return supportedFileType;
      }
    }
    return this.defaultFileType;
  }

  fileEnding: string;


  constructor(fileEnding: string) {
    this.fileEnding = fileEnding;
  }
}
